// lib/services.js
// সব service এর data এক জায়গায় রাখা হয়েছে

export const SERVICES = [
  {
    id: 'web-design',
    name: 'Web Design & Development',
    description: 'Custom, responsive websites built with modern technologies. From landing pages to full web applications tailored to your brand.',
    price: 299,
    duration: '3–7 days',
    icon: '🖥️',
    features: ['Custom UI/UX Design', 'Mobile Responsive', 'SEO Optimized', 'CMS Integration'],
    popular: false,
  },
  {
    id: 'seo-marketing',
    name: 'SEO & Digital Marketing',
    description: 'Boost your online visibility with data-driven SEO strategies, content marketing, and targeted ad campaigns.',
    price: 199,
    duration: '1–2 weeks',
    icon: '📈',
    features: ['Keyword Research', 'On-page SEO', 'Google Ads Setup', 'Monthly Report'],
    popular: true,
  },
  {
    id: 'mobile-app',
    name: 'Mobile App Development',
    description: 'Cross-platform iOS & Android apps that deliver seamless user experiences using React Native.',
    price: 499,
    duration: '2–4 weeks',
    icon: '📱',
    features: ['iOS & Android', 'Push Notifications', 'API Integration', 'App Store Deploy'],
    popular: false,
  },
  {
    id: 'brand-identity',
    name: 'Brand Identity Design',
    description: 'Memorable logos, color palettes, and brand guidelines that make your business stand out from the competition.',
    price: 149,
    duration: '2–5 days',
    icon: '🎨',
    features: ['Logo Design', 'Color Palette', 'Brand Guidelines', 'Social Media Kit'],
    popular: false,
  },
  {
    id: 'cloud-devops',
    name: 'Cloud & DevOps Setup',
    description: 'Deploy, scale, and secure your infrastructure on AWS, GCP, or Azure with CI/CD pipelines and monitoring.',
    price: 399,
    duration: '3–10 days',
    icon: '☁️',
    features: ['Cloud Architecture', 'Docker & Kubernetes', 'CI/CD Pipeline', '24/7 Monitoring'],
    popular: false,
  },
  {
    id: 'ai-integration',
    name: 'AI & Automation Integration',
    description: 'Embed AI-powered features into your products – chatbots, recommendation engines, data analysis, and more.',
    price: 599,
    duration: '1–3 weeks',
    icon: '🤖',
    features: ['OpenAI Integration', 'Custom Chatbots', 'Data Pipelines', 'Workflow Automation'],
    popular: true,
  },
]
